[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Asynchronous, GTK+-based, GUI library, inspired by Elm, written in Rust"
homepage = "https://relm.antoyo.xyz/"
documentation = "https://docs.rs/relm/"
license = "MIT"
name = "relm"
readme = "README.adoc"
repository = "https://github.com/antoyo/relm"
version = "0.24.1"
edition = "2018"

[dependencies]
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs-core" }
fragile = "2.0"
gio = { git = "https://github.com/gtk-rs/gtk-rs-core" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core" }
glib-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gtk = { git = "https://github.com/nikescar/gtk3-rs.git", version = "0.19.0" }
libc = "^0.2.54"
log = "^0.4.6"
target-lexicon = "0.13.3"

[features]
hidpi = []
