[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "webkit-test"
version = "0.1.0"
edition = "2024"

[dependencies]
glib = "^0.18"
gtk = "^0.18"
webkit2gtk = "^2.0"

[dependencies.relm]
default-features = false
path = "../../.."

[dependencies.relm-derive]
path = "../../../relm-derive"
