[package]
name = "circle_drawer"
version = "0.1.0"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
edition = "2024"

[dependencies]
glib = "^0.18.5"
gtk = { version = "^0.18.2", features = ["v3_24"] }
gdk = "^0.18.2"
cairo-rs = "^0.18.5"

[dependencies.gio]
features = ["v2_58"]
version = "^0.18.4"

[dependencies.relm]
path = "../../../.."

[dependencies.relm-derive]
path = "../../../../relm-derive"
